import { observable } from 'mobx';

class LanguageStore {
    @observable English = {
      say: 'Say',
      inn: 'in',
      tap: 'Tap to Record',
      listening: 'Listening...',
      again: 'Tap to Record Again',
      appSettings: 'App Settings',
      wordSettings: 'Word Settings',
      record: 'Record',
      seconds: 'seconds',
      reloadAfter: 'Reload after',
      words: 'words',
      langList: [
        	'English',
        	'Afrikanns',
        	'Albanian',
        	'Arabic',
        	'Armenian',
        	'Basque',
        	'Bengali',
        	'Bulgarian',
        	'Catalan',
        	'Cambodian',
        	'Chinese (Mandarin)',
        	'Croatian',
        	'Czech',
        	'Danish',
        	'Dutch',
        	'Spanish',
        	'Estonian',
        	'Fiji',
        	'Finnish',
        	'French',
        	'Georgian',
        	'German',
        	'Greek',
        	'Gujarati',
        	'Hebrew',
        	'Hindi',
        	'Hungarian',
        	'Icelandic',
        	'Indonesian',
        	'Irish',
        	'Italian',
        	'Japanese',
        	'Javanese',
        	'Korean',
        	'Latin',
        	'Latvian',
        	'Lithuanian',
        	'Macedonian',
        	'Malay',
        	'Malayalam',
        	'Maltese',
        	'Maori',
        	'Marathi',
        	'Mongolian',
        	'Nepali',
        	'Norwegian',
        	'Persian',
        	'Polish',
        	'Portuguese',
        	'Punjabi',
        	'Quechua',
        	'Romanian',
        	'Russian',
        	'Samoan',
        	'Serbian',
        	'Slovak',
        	'Slovenian',
        	'Swahili',
        	'Swedish',
        	'Tamil',
        	'Tatar',
        	'Telugu',
        	'Thai',
        	'Tibetan',
        	'Tonga',
        	'Turkish',
        	'Ukranian',
        	'Urdu',
        	'Uzbek',
        	'Vietnamese',
        	'Welsh',
        	'Xhosa'
      ]
    };

    @observable Español = {
      say: 'Di',
      inn: 'en',
      tap: 'Aprieta para grabar',
      listening: 'Escuchando...',
      again: 'Aprieta para volver a grabar',
      appSettings: 'Opciones de Grabación',
      wordSettings: 'Opciones Avanzadas',
      record: 'Graba',
      seconds: 'segundos',
      reloadAfter: 'Cargar cada',
      words: 'palabras',
      langList: [
        'Español',
        'Catalán',
        'Inglés',
        'Afrikanns',
        'Albanés',
        'Alemán',
        'Árabe',
        'Armenio',
        'Vasco',
        'Bengali',
        'Búlgaro',
        'Camboyano',
        'Coreano',
        'Croata',
        'Danés',
        'Estonio',
        'Eslovaco',
        'Esloveno',
        'Fiji',
        'Finlandés',
        'Francés',
        'Georgiano',
        'Griego',
        'Gujarati',
        'Hebreo',
        'Hindi',
        'Holandés',
        'Húngaro',
        'Islandés',
        'Indonesio',
        'Irlandés',
        'Italiano',
        'Japonés',
        'Javanés',
        'Latín',
        'Letón',
        'Lituano',
        'Macedonio',
        'Malayo',
        'Malayalam',
        'Maltés',
        'Maori',
        'Marathi',
        'Mongol',
        'Nepalí',
        'Noruego',
        'Persa',
        'Polaco',
        'Portugués',
        'Punjabi',
        'Quechua',
        'Rumano',
        'Ruso',
        'Samoano',
        'Serbio',
        'Swahili',
        'Sueco',
        'Tamil',
        'Tártaro',
        'Telugu',
        'Tailandés',
        'Tibetano',
        'Tonga',
        'Turco',
        'Checo',
        'Ucraniano',
        'Urdu',
        'Uzbeko',
        'Vietnamita',
        'Galés',
        'Xhosa',
        'Chino (mandarín)',
      ]
    };

    @observable Català = {
      say: 'Digues',
      inn: 'en',
      tap: 'Prem per gravar',
      listening: 'Escoltant...',
      again: 'Prem per tornar a gravar',
      appSettings: 'Opcions de Gravació',
      wordSettings: 'Opcions Avançades',
      record: 'Grava',
      seconds: 'segons',
      reloadAfter: 'Carrega cada',
      words: 'paraules',
      langList: [
        	'Català',
        	'Anglès',
        	'Afrikanns',
        	'Albanès',
        	'Alemany',
        	'Àrab',
        	'Armeni',
        	'Basc',
        	'Bengali',
        	'Búlgar',
        	'Cambodjà',
        	'Coreà',
        	'Croat',
        	'Danès',
        	'Estonià',
        	'Eslovac',
        	'Eslovè',
        	'Espanyol',
        	'Fiji',
        	'Finlandès',
        	'Francès',
        	'Georgiano',
        	'Grec',
        	'Gujarati',
        	'Hebreu',
        	'Hindi',
        	'Holandès',
        	'Hongarès',
        	'Islandesa',
        	'Indonesi',
        	'Irlandès',
        	'Italià',
        	'Japonès',
        	'Javanès',
        	'Llatí',
        	'Letó',
        	'Lituà',
        	'Macedoni',
        	'Malai',
        	'Malayalam',
        	'Maltès',
        	'Maori',
        	'Marathi',
        	'Mongol',
        	'Nepalès',
        	'Noruec',
        	'Persa',
        	'Polonès',
        	'Portuguès',
        	'Punjabi',
        	'Quechua',
        	'Romanès',
        	'Rus',
        	'Samoà',
        	'Serbi',
        	'Suahili',
        	'Suec',
        	'Tàmil',
        	'Tàrtar',
        	'Telugu',
        	'Tailandès',
        	'Tibetà',
        	'Tonga',
        	'Turc',
        	'Txec',
        	'Ucraïnès',
        	'Urdu',
        	'Uzbek',
        	'Vietnamita',
        	'Galés',
        	'Xhosa',
        	'Xinès (mandarí)',
      ]
    };
}

const languageSet = new LanguageStore();
export default languageSet;
